### ISSUE TITLE
Different names for the same argument

### ISSUE THREAD

**Issue by qdread** [NEON-biodiversity/Ostats#2]
Issue originally mentioned by @yyue-r in an email.

There are some cases where a function argument changes names as it passes through different layers of functions. For example `n` is also passed as `N`, and `norm` as `normal`. I need to check to remind myself whether this was done intentionally. Hopefully we can figure out a way to make things consistent without causing errors or problems.

**Comment by yyue-r** [comment]
I checked the changes over time and I think Sydne made the first changes in arguments on June 15 (the second commit). To make sure the functions run, I changed arguments for a few other functions too.

Functions that uses "normal" and "N": pairwise_overlap, community_overlap_merged (these two run without problem), community_overlap (community_overlap is the first function in densityoverlap, and I changed it to run it to compare the result with the merged function)

Functions that uses "normal"  circular_overlap, circular_overlap_24hour (I was going to change n to N for circular_overlap but I will hold on for now, in the documentation I said "N")

 Sorry for the confusion but I can revert the changes if needed!

**Comment by qdread** [comment]
OK I have an idea here. I think the argument names are fine. I'm not sure why I made them different before, though I do seem to remember doing it intentionally.
But what we should do to clean things up is include an ellipsis `...` in the arguments to `pairwise_overlap` to enable passing as many arguments as we want to `density`. Then we need to put ellipsis in any other higher up functions so that we can go all the way up and pass those arguments from `Ostats` so that they pass through all the layers and get to the `pairwise_overlap` function. 

I can do this at some point or if you want to do it @yyue-r you can work on it. Let me know if this does not make sense or you need clarification!

**Comment by qdread** [comment]
I've started to work on this in a branch called [clean_up_args](https://github.com/NEON-biodiversity/Ostats/tree/clean_up_args) because I did not want to mess up what you all were doing too much. Hopefully it will not cause too much conflict and we can merge later. Basically I am getting rid of the bw and N arguments and replacing it with a `...` argument in `Ostats` where the user can put in bw, N, and whatever else they want. It will pass down through `community_overlap_merged` and through to `pairwise_overlap` or `circular`.

**Comment by qdread** [comment]
@yyue-r @isafluck OK, check out the commit d008e9d ! I think this gets rid of the bw and N arguments everywhere. The user can now put in whatever arguments they want to pass to `density()`. This is useful because there are other arguments they might want to send to `density()`, such as `adjust` and `kernel`. Now they have the option. 

I haven't tested the code properly yet so I will leave this issue open until we are sure it all works. Feel free to close whenever it is tested.

**Comment by yyue-r** [comment]
@qdread Hi Quentin, thank you so much for cleaning up the arguments! Since it solves the problem of "n" and "N", should I choose one between "norm" and "normal" and make it consistent across the package?

**Comment by qdread** [comment]
@yyue-r Yeah I think that's fine. I think most of the functions now have the name `normal`. I tried to get rid of `norm` wherever I could, so if you see `norm` anymore go ahead and get rid of it! :-D

**Comment by yyue-r** [comment]
@qdread  Ok!

**Comment by qdread** [comment]
@yyue-r  I think this problem is pretty much cleared up by the edits referenced in #7 so we can probably close this too ...
