### ISSUE TITLE
Remove .Rproj.user from commits

### ISSUE THREAD

**Issue by qdread** [NEON-biodiversity/Ostats#24]
@yyue-r @isafluck 

I have noticed that there is a file called `.Rproj.user` in the repository. That file should not be included in any commits because it is an internal "hidden" file that should exist on all of our individual machines but should not be pulled and pushed when we commit to the remote repository. It is in the `.gitignore` so future commits should not include it. Please make sure you do not commit any more changes to this file. All of use should have a different version. It contains information such as paths to local files on our individual machines, and the state of the windows of RStudio the last time we opened the project on our computers, etc. I will try to resolve it on my end as well.

**Comment by qdread** [comment]
Can everyone please run the following on the terminal in their local Ostats git repository directory?

`git rm -r --cached .Rproj.user/`

This will ensure that the local changes of .Rproj.user will stop tracking on the remote repository!

**Comment by isafluck** [comment]
Hello, Quentin!
I got the following message
![image](https://user-images.githubusercontent.com/65627563/97609652-9f47e080-19f2-11eb-8b2f-3cfad5888a79.png)

What is wrong?

**Comment by qdread** [comment]
Follow up -- if you are on Windows you may not be able to run this in your terminal in rstudio, you will need to run it in git bash in the appropriate directory.

**Comment by isafluck** [comment]
Ok, I downloaded Git and ran the command! Now I think it worked.
![image](https://user-images.githubusercontent.com/65627563/97615374-fbfac980-19f9-11eb-95ec-ed97f4439b7f.png)

From now on I will be careful not to commit and push any files related to .Rporj .

**Comment by qdread** [comment]
Great! 🥂

**Comment by qdread** [comment]
@yyue-r Just to follow up, were you ever able to do this or do you still need help getting it to run?

**Comment by yyue-r** [comment]
@qdread I did it and my computer tells me that no .Rproj files can be found. So I guess it should be fine?

**Comment by qdread** [comment]
Thanks! I'll go ahead and close this.
