### ISSUE TITLE
Decide whether to get rid of some old functions

### ISSUE THREAD

**Issue by qdread** [NEON-biodiversity/Ostats#33]
The functions 

- `Ostat_regional()`
- `community_overlap_noitv()`
- `Ostat2longform()`

were functions that I wrote for different customized questions we came up with in the process of our work on the overlap stuff. I stuck them in the package to begin with because I just dumped all the code in there. But they have not been maintained or improved since then, and other improvements to the code may have caused them to break. So for now I am moving them to a folder ignored in the R build, and we can decide later whether to completely remove them from the pkg or not.

**Comment by qdread** [comment]
@sydnerecord @yyue-r @isafluck I apologize if this wastes some work you did, since you have a nice example in the vignette and some nice documentation for the `Ostats_regional()` function. But I'm not sure it is that useful to include `Ostats_regional()` in the package since it's a little bit confusing what exactly it's doing, and it would likely not be used very much by users. I could go either way on it, so I was curious if any of you had a strong opinion on it. Any comments welcome.

As for the other two functions, `community_overlap_noitv()` and `Ostat2longform()`, I am going to go ahead and not include them in the package because they were just functions I wrote a long time ago for a specific purpose that will not be generally useful to users of the package. Sound OK?

**Comment by sydnerecord** [comment]
@qdread All of this sounds fine to me for the general vignette that will accompany the publication. However, I think we should save the old version of the vignette we worked (with a different name) on a branch for our team to access as some of those functions will be useful to us as we move the project forward.

**Comment by qdread** [comment]
@sydnerecord I had saved the section that I removed from the vignette in [this document](https://github.com/NEON-biodiversity/Ostats/blob/master/internal_docs/regional_vignette_excerpt.txt) on the repo. So all the text you worked on is still accessible :-D
