### ISSUE TITLE
Create pkgdown site

### ISSUE THREAD

**Issue by qdread** [NEON-biodiversity/Ostats#40]
Obviously every good package needs a pkgdown site 😆 

@billspat I will build a pkgdown site for the Ostats package, which should be posted at neon-biodiversity.github.io/Ostats. Once I do, can you link to it from the main page?

**Comment by billspat** [comment]
yes will do!  

we will have to mark it in the config file for the Hugo site generator to ignore that folder for processing, and just pass it over  to the site untouched.   

If we think other projects may have pkgdown, bookdown, or even single R notebook files, then I think we need a sub folder for projects, 

`neon-biodiversity.github.io/projects/Ostats`

then there is one point in the site where all projects go, and won't be mixed with folders for Hugo cms processing. 

I can then link to projects in a sub-menu under "our research" 

if there is any "news" related to Ostats (recent CRAN release, paper, etc) or any other projects, we can create a news item as well which shows up in the "Research Highlights" section of the home page.

**Comment by qdread** [comment]
@billspat thanks! Let me know if there is any additional configuration I need to set up. I just built the page which is live at https://neon-biodiversity.github.io/Ostats/. I used the standard github pages settings for the `Ostats` repository, it's set to build github page from the `docs/` folder on `master`. I'll let you tinker with it if you need to make any other changes to the configuration.

**Comment by qdread** [comment]
Yes go ahead and add the pic! I made a PR with a small edit to your blurb. Thanks!

**Comment by billspat** [comment]
thanks  @qdread  for the PR  - that made it really easy to merge, rebuild  and deploy.  and thanks for adding our first package!!  inspiration  

https://neon-biodiversity.github.io/post/ostats-package/
