### ISSUE TITLE
Document pitcher traits

### ISSUE THREAD

**Issue by qdread** [NEON-biodiversity/Ostats#42]
This should be a fairly easy one for you @sydnerecord .

We need to have a documentation file for the pitcher plant traits. I made a placeholder one, [pitcher_traits.R](https://github.com/NEON-biodiversity/Ostats/blob/master/R/pitcher_traits.R). Can you please write the documentation for this, analogous to the [ant data documentation](https://github.com/NEON-biodiversity/Ostats/blob/master/R/ant_data.R) and the [smammal data documentation](https://github.com/NEON-biodiversity/Ostats/blob/master/R/small_mammal_data.R)? thanks!

**Comment by sydnerecord** [comment]
Sorry this has taken so long! It's done now.
