### ISSUE TITLE
details on documentation Ostats

### ISSUE THREAD

**Issue by isafluck** [NEON-biodiversity/Ostats#6]
Hello!
I have tried to update a small detail in the Ostat function documentation, but when I tried to document it, an error happened with the figshare link. I don't know why... maybe it was nothing but maybe you can check it.

The (very little and silly) detail I was trying to change is that the name I use in academic works is Isadora Essig Fluck and not Isadora Fluck Essig. So please if you can refer to me on the next steps as Isadora E. Fluck, I will appreciate it :)

**Comment by qdread** [comment]
@isafluck I apologize, I just now saw this issue. Is this still something you need help with? And no need to say it's a silly detail, it's very important to get names right!

**Comment by sydnerecord** [comment]
Added Isadora's correct name to author list on Readme file and doublechecked names on vignette authors.
